name: Build and Package Legal Kill
 
on:
  push:
    branches:
      - release/sit
  pull_request:
    branches:
      - release/sit
 
jobs:
  build:
    name: Build Patch
    runs-on: ubuntu-latest
    timeout-minutes: 180
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
 
    - name: Setup Node.js (v8)
      uses: actions/setup-node@v3
      with:
        node-version: 8
        cache: 'npm'
 
    - name: Install Dependencies
      run: |
        echo "Installing with npm..."
        npm install
 
    - name: Build Project
      run: |
        echo "Running npm build..."
        npm run build
 
    - name: Package Build
      run: |
        echo "Creating package.zip..."
        zip -r package.zip . -x '*.git*'
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: package.zip
 
