name: Build and Package Legal Kill
 
on:
  push:
    branches:
      - release/sit
  pull_request:
    branches:
      - release/sit
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
 
jobs:
  build:
    name: Build Patch
    runs-on: ubuntu-latest
    timeout-minutes: 180
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
 
    - name: Setup Node.js (v8)
      uses: actions/setup-node@v3
      with:
        node-version: 8
        cache: 'npm'
 
    - name: Install Dependencies
      run: npm install
 
    - name: Build Project
      run: npm run build
 
    - name: Archive Build Output
      run: |
       zip -r package.zip . -x '*.git*' 'node_modules/*' '*.github*'
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: legal-kill-package
        path: package.zip
